// <auto-generated />
namespace MyHabbits.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class DeletedCustomer_taskFromCustomerTaskHistory : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DeletedCustomer_taskFromCustomerTaskHistory));
        
        string IMigrationMetadata.Id
        {
            get { return "201709270037108_DeletedCustomer_taskFromCustomerTaskHistory"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
